Repository corgibytes/freshli-cli, pull requests merged in 2022-07, with the labels that each got.

#111 Improve contributing guide
  CONTRIBUTING.md
Labels: documentation

#96 Added agents detect command issue #61
  .codeclimate.yml
  Corgibytes.Freshli.Cli.Test/Corgibytes.Freshli.Cli.Test.csproj
  Corgibytes.Freshli.Cli.Test/Fixtures/EnvironmentTest/OtherSampleFile.txt
  Corgibytes.Freshli.Cli.Test/Fixtures/EnvironmentTest/SampleFile.txt
  Corgibytes.Freshli.Cli.Test/Functionality/AgentsDetectorTest.cs
  Corgibytes.Freshli.Cli.Test/Functionality/EnvironmentTest.cs
  Corgibytes.Freshli.Cli.Test/Functionality/MockEnvironment.cs
  Corgibytes.Freshli.Cli/CommandOptions/EmptyCommandOptions.cs
  Corgibytes.Freshli.Cli/CommandRunners/AgentsCommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/Cache/DestroyCommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/Cache/PrepareCacheRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/CacheCommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/CommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/GitCommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/ICommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/ScanCommandRunner.cs
  Corgibytes.Freshli.Cli/Commands/AgentsCommand.cs
  Corgibytes.Freshli.Cli/Commands/AgentsDetector.cs
  Corgibytes.Freshli.Cli/Commands/Cache/DestroyCommand.cs
  Corgibytes.Freshli.Cli/Commands/Cache/PrepareCommand.cs
  Corgibytes.Freshli.Cli/Commands/GitCommand.cs
  Corgibytes.Freshli.Cli/Commands/MainCommand.cs
  Corgibytes.Freshli.Cli/Commands/RunnableCommand.cs
  Corgibytes.Freshli.Cli/Commands/ScanCommand.cs
  Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj
  Corgibytes.Freshli.Cli/Functionality/CacheContext.cs
  Corgibytes.Freshli.Cli/Functionality/Environment.cs
  Corgibytes.Freshli.Cli/Functionality/IEnvironment.cs
  Corgibytes.Freshli.Cli/IoC/FreshliServiceBuilder.cs
  Corgibytes.Freshli.Cli/Program.cs
  Corgibytes.Freshli.Cli/Resources/CliOutput.Designer.cs
  Corgibytes.Freshli.Cli/Resources/CliOutput.es.resx
  Corgibytes.Freshli.Cli/Resources/CliOutput.resx
  Gemfile.lock
  bin/format.rb
  bin/test.rb
  features/agents.feature
  features/step_definitions/database.rb
  features/step_definitions/environment.rb
Labels: enhancement

#119 Use CliWrap instead of System.Diagnostics
  Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj
  Corgibytes.Freshli.Cli/Functionality/Git.cs
Labels: refactoring

#112 Calculate libyear
  .codeclimate.yml
  Corgibytes.Freshli.Cli.Test/Commands/MockAgentsDetector.cs
  Corgibytes.Freshli.Cli.Test/Commands/MockAgentsReader.cs
  Corgibytes.Freshli.Cli.Test/DependencyManagers/AgentsRepositoryTest.cs
  Corgibytes.Freshli.Cli.Test/DependencyManagers/MockAgentsRepository.cs
  Corgibytes.Freshli.Cli.Test/Functionality/LeapYearsTest.cs
  Corgibytes.Freshli.Cli.Test/Functionality/LibYearTest.cs
  Corgibytes.Freshli.Cli.Test/Functionality/MockFileReader.cs
  Corgibytes.Freshli.Cli.Test/Functionality/ReadCycloneDxFileTest.cs
  Corgibytes.Freshli.Cli.Test/Services/CalculateLibYearForCycloneDxFileTest.cs
  Corgibytes.Freshli.Cli/CommandOptions/ComputeLibYearCommandOptions.cs
  Corgibytes.Freshli.Cli/CommandRunners/AgentsCommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/ComputeLibYearCommandRunner.cs
  Corgibytes.Freshli.Cli/Commands/AgentsDetector.cs
  Corgibytes.Freshli.Cli/Commands/ComputeLibYearCommand.cs
  Corgibytes.Freshli.Cli/Commands/IAgentsDetector.cs
  Corgibytes.Freshli.Cli/Commands/MainCommand.cs
  Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj
  Corgibytes.Freshli.Cli/DependencyManagers/AgentsRepository.cs
  Corgibytes.Freshli.Cli/DependencyManagers/IDependencyManagerRepository.cs
  Corgibytes.Freshli.Cli/Exceptions/LatestVersionNotFoundException.cs
  Corgibytes.Freshli.Cli/Exceptions/ReleaseDateNotFoundException.cs
  Corgibytes.Freshli.Cli/ExtensionMethods/PackageUrlsExtensions.cs
  Corgibytes.Freshli.Cli/Functionality/CycloneDxFileReaderFromFileReaderSystem.cs
  Corgibytes.Freshli.Cli/Functionality/IFileReader.cs
  Corgibytes.Freshli.Cli/Functionality/JsonCycloneDX.cs
  Corgibytes.Freshli.Cli/Functionality/LeapYears.cs
  Corgibytes.Freshli.Cli/Functionality/LibYear.cs
  Corgibytes.Freshli.Cli/Functionality/Package.cs
  Corgibytes.Freshli.Cli/Functionality/PackageLibYear.cs
  Corgibytes.Freshli.Cli/Functionality/ReadCycloneDxFile.cs
  Corgibytes.Freshli.Cli/IoC/FreshliServiceBuilder.cs
  Corgibytes.Freshli.Cli/Program.cs
  Corgibytes.Freshli.Cli/Resources/CliOutput.Designer.cs
  Corgibytes.Freshli.Cli/Resources/CliOutput.es.resx
  Corgibytes.Freshli.Cli/Resources/CliOutput.resx
  Corgibytes.Freshli.Cli/Services/AgentReader.cs
  Corgibytes.Freshli.Cli/Services/CalculateLibYearFromCycloneDxFile.cs
  Corgibytes.Freshli.Cli/Services/IAgentReader.cs
  Corgibytes.Freshli.Cli/Services/ICalculateLibYearFromFile.cs
  README.md
  features/compute_libyear.feature
  features/help.feature
Labels: enhancement

#116 Checkout history
  .codeclimate.yml
  Corgibytes.Freshli.Cli.Test/Commands/Git/CheckoutHistoryCommandTest.cs
  Corgibytes.Freshli.Cli.Test/Commands/GitCommandTest.cs
  Corgibytes.Freshli.Cli.Test/Functionality/GitCommitIdentifierTest.cs
  Corgibytes.Freshli.Cli/CommandOptions/Git/CheckoutHistoryCommandOptions.cs
  Corgibytes.Freshli.Cli/CommandOptions/Git/GitCloneCommandOptions.cs
  Corgibytes.Freshli.Cli/CommandOptions/Git/GitCommandOptions.cs
  Corgibytes.Freshli.Cli/CommandRunners/Git/CheckoutHistoryCommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/Git/GitCloneCommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/GitCommandRunner.cs
  Corgibytes.Freshli.Cli/Commands/Git/CheckoutHistoryCommand.cs
  Corgibytes.Freshli.Cli/Commands/Git/GitCloneCommand.cs
  Corgibytes.Freshli.Cli/Commands/GitCommand.cs
  Corgibytes.Freshli.Cli/Commands/MainCommand.cs
  Corgibytes.Freshli.Cli/DataModel/CacheContext.cs
  Corgibytes.Freshli.Cli/DataModel/CachedGitSource.cs
  Corgibytes.Freshli.Cli/DataModel/CachedProperty.cs
  Corgibytes.Freshli.Cli/Functionality/Cache.cs
  Corgibytes.Freshli.Cli/Functionality/CachedGitRepo.cs
  Corgibytes.Freshli.Cli/Functionality/Git/GitArchive.cs
  Corgibytes.Freshli.Cli/Functionality/Git/GitCommitIdentifier.cs
  Corgibytes.Freshli.Cli/Functionality/Git/GitSource.cs
  Corgibytes.Freshli.Cli/IoC/FreshliServiceBuilder.cs
  Corgibytes.Freshli.Cli/Migrations/20220516190023_InitialCreate.Designer.cs
  Corgibytes.Freshli.Cli/Migrations/20220524202324_GitRepository.Designer.cs
  Corgibytes.Freshli.Cli/Migrations/20220524202324_GitRepository.cs
  Corgibytes.Freshli.Cli/Migrations/CacheContextModelSnapshot.cs
  Corgibytes.Freshli.Cli/Repositories/CachedGitSourceRepository.cs
  Corgibytes.Freshli.Cli/Repositories/ICachedGitSourceRepository.cs
  Corgibytes.Freshli.Cli/Resources/CliOutput.Designer.cs
  Corgibytes.Freshli.Cli/Resources/CliOutput.es.resx
  Corgibytes.Freshli.Cli/Resources/CliOutput.resx
  Corgibytes.Freshli.Cli/Services/AgentReader.cs
  features/cache.feature
  features/checkout_history.feature
  features/help.feature
  features/step_definitions/filesystem.rb
Labels: enhancement

#130 Create mock freshli agent in Ruby
  bin/freshli-agent-mock.rb
Labels: testing

#117 Enable Nullable
  .codeclimate.yml
  .config/dotnet-tools.json
  .gitignore
  Corgibytes.Freshli.Cli.Test/CommandOptions/ScanCommandOptionsTest.cs
  Corgibytes.Freshli.Cli.Test/Common/TestHelpers.cs
  Corgibytes.Freshli.Cli.Test/Corgibytes.Freshli.Cli.Test.csproj
  Corgibytes.Freshli.Cli.Test/Extensions.cs
  Corgibytes.Freshli.Cli.Test/Formatters/OutputFormatterTest.cs
  Corgibytes.Freshli.Cli.Test/Functionality/MockFileReader.cs
  Corgibytes.Freshli.Cli.Test/OutputStrategies/OutputStrategiesTest.cs
  Corgibytes.Freshli.Cli/CommandOptions/CommandOptions.cs
  Corgibytes.Freshli.Cli/CommandOptions/ComputeLibYearCommandOptions.cs
  Corgibytes.Freshli.Cli/CommandOptions/Git/CheckoutHistoryCommandOptions.cs
  Corgibytes.Freshli.Cli/CommandOptions/Git/GitCloneCommandOptions.cs
  Corgibytes.Freshli.Cli/CommandOptions/ScanCommandOptions.cs
  Corgibytes.Freshli.Cli/CommandRunners/AgentsCommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/CommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/ComputeLibYearCommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/ScanCommandRunner.cs
  Corgibytes.Freshli.Cli/Commands/RunnableCommand.cs
  Corgibytes.Freshli.Cli/Commands/ScanCommand.cs
  Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj
  Corgibytes.Freshli.Cli/DataModel/CacheContext.cs
  Corgibytes.Freshli.Cli/DataModel/CachedGitSource.cs
  Corgibytes.Freshli.Cli/DataModel/CachedProperty.cs
  Corgibytes.Freshli.Cli/Formatters/OutputFormatter.cs
  Corgibytes.Freshli.Cli/Formatters/YamlOutputFormatter.cs
  Corgibytes.Freshli.Cli/Functionality/CycloneDxFileReaderFromFileReaderSystem.cs
  Corgibytes.Freshli.Cli/Functionality/Environment.cs
  Corgibytes.Freshli.Cli/Functionality/Git/GitSource.cs
  Corgibytes.Freshli.Cli/Functionality/JsonCycloneDX.cs
  Corgibytes.Freshli.Cli/Functionality/PackageLibYear.cs
  Corgibytes.Freshli.Cli/Migrations/20220715164205_Nullable.Designer.cs
  Corgibytes.Freshli.Cli/Migrations/20220715164205_Nullable.cs
  Corgibytes.Freshli.Cli/Migrations/CacheContextModelSnapshot.cs
  Corgibytes.Freshli.Cli/OutputStrategies/FileOutputStrategy.cs
  README.md
  bin/lint.rb
Labels: refactoring

#94 Translation Strings
  Corgibytes.Freshli.Cli/CommandOptions/Git/CheckoutHistoryCommandOptions.cs
  Corgibytes.Freshli.Cli/CommandRunners/Cache/DestroyCommandRunner.cs
  Corgibytes.Freshli.Cli/CommandRunners/Cache/PrepareCacheRunner.cs
  Corgibytes.Freshli.Cli/Commands/Cache/DestroyCommand.cs
  Corgibytes.Freshli.Cli/Commands/Cache/PrepareCommand.cs
  Corgibytes.Freshli.Cli/Commands/CacheCommand.cs
  Corgibytes.Freshli.Cli/Commands/Git/CheckoutHistoryCommand.cs
  Corgibytes.Freshli.Cli/Commands/Git/GitCloneCommand.cs
  Corgibytes.Freshli.Cli/Commands/GitCommand.cs
  Corgibytes.Freshli.Cli/Commands/MainCommand.cs
  Corgibytes.Freshli.Cli/Commands/ScanCommand.cs
  Corgibytes.Freshli.Cli/DataModel/CachedGitSource.cs
  Corgibytes.Freshli.Cli/Functionality/Cache.cs
  Corgibytes.Freshli.Cli/Functionality/Git/GitSource.cs
  Corgibytes.Freshli.Cli/Functionality/PackageLibYear.cs
  Corgibytes.Freshli.Cli/Resources/CliOutput.Designer.cs
  Corgibytes.Freshli.Cli/Resources/CliOutput.es.resx
  Corgibytes.Freshli.Cli/Resources/CliOutput.resx
  features/help.feature
Labels: enhancement

#121 Compute history
  Corgibytes.Freshli.Cli.Test/Commands/Git/ComputeHistoryCommandTest.cs
  Corgibytes.Freshli.Cli.Test/Functionality/Git/ComputeHistoryTest.cs
  Corgibytes.Freshli.Cli.Test/Functionality/Git/MockListCommits.cs
  Corgibytes.Freshli.Cli/CommandOptions/ComputeHistoryCommandOptions.cs
  Corgibytes.Freshli.Cli/CommandRunners/Git/ComputeHistoryCommandRunner.cs
  Corgibytes.Freshli.Cli/Commands/Git/ComputeHistoryCommand.cs
  Corgibytes.Freshli.Cli/Commands/GitCommand.cs
  Corgibytes.Freshli.Cli/Functionality/Git/ComputeHistory.cs
  Corgibytes.Freshli.Cli/Functionality/Git/GitCommit.cs
  Corgibytes.Freshli.Cli/Functionality/Git/HistoryIntervalStop.cs
  Corgibytes.Freshli.Cli/Functionality/Git/IListCommits.cs
  Corgibytes.Freshli.Cli/Functionality/Git/ListCommits.cs
  Corgibytes.Freshli.Cli/IoC/FreshliServiceBuilder.cs
  features/compute_history.feature
Labels: enhancement
